packages:
- .
- location:
    git: https://github.com/luqui/graphics-drawingcombinators
    commit: 3c3a9a48646a4ad10e001535391bda5737768711

resolver: nightly-2015-08-06
extra-deps:
- FTGL-2.1
- TraceUtils-0.1.0.2
- TypeCompose-0.9.10
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- leveldb-haskell-0.6.3
- stb-image-0.2.1
- bindings-GLFW-3.1.1.4
- GLFW-b-1.4.7.3
