packages:
- .
- location:
    git: https://github.com/luqui/graphics-drawingcombinators
    commit: 3c3a9a48646a4ad10e001535391bda5737768711
- location:
    git: https://github.com/Peaker/bindings-GLFW
    commit: 98e3fd9a71ce673c1fcc741acae8b8ca1550c5c1
- location:
    git: https://github.com/Peaker/GLFW-b
    commit: 142d6cdd2dd7c323a8c4a04a9dfdc4f07920408f

resolver: nightly-2015-08-06
extra-deps:
- FTGL-2.1
- TraceUtils-0.1.0.2
- TypeCompose-0.9.10
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- leveldb-haskell-0.6.3
- stb-image-0.2.1
